title: AI Conference Deadlines
# email:
description: Countdowns to conference deadlines
author: Malta Lab

domain: ""
baseurl: "/ai-deadlines"

twitter_username: malta-lab
twitter_hashtag: maltalab
github_username: malta-lab
github_repo: ai-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
